name: jarvis
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=1.3.0=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py36_0
  - cffi=1.14.0=py36h2e261b9_0
  - chardet=3.0.4=py36_1003
  - cloudpickle=1.3.0=py_0
  - cryptography=2.8=py36h1ba5d50_0
  - cycler=0.10.0=py36_0
  - cython=0.29.15=py36he6710b0_0
  - cytoolz=0.10.1=py36h7b6447c_0
  - dask-core=2.14.0=py_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.2=py_0
  - dill=0.3.1.1=py36_0
  - expat=2.2.9=he1b5a44_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - gdcm=2.8.9=py36h71b2a6d_0
  - glib=2.56.2=hd408876_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.10.0=py36h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h211956c_0
  - idna=2.9=py_1
  - imageio=2.8.0=py_0
  - intel-openmp=2020.0=166
  - ipdb=0.12.3=py_0
  - ipython=7.13.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - jedi=0.16.0=py36_1
  - joblib=0.14.1=py_0
  - jpeg=9c=h14c3975_1001
  - json-c=0.13.1=h14c3975_1001
  - kiwisolver=1.1.0=py36he6710b0_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libjpeg-turbo=2.0.3=h516909a_1
  - libpng=1.6.37=hed695b0_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=1.0.3=h1bed415_2
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - lz4-c=1.8.3=he1b5a44_1001
  - matplotlib=3.1.3=py36_0
  - matplotlib-base=3.1.3=py36hef1b27d_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.15=py36ha843d7b_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - ncurses=6.2=he6710b0_0
  - networkx=2.4=py_0
  - numpy-base=1.18.1=py36hde5b4d6_1
  - olefile=0.46=py36_0
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1=h7b6447c_0
  - pandas=1.0.3=py36h0573a6f_0
  - parso=0.6.2=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=7.0.0=py36hb39fc2d_0
  - pip=20.0.2=py36_1
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - ptyprocess=0.6.0=py36_0
  - pycparser=2.20=py_0
  - pydicom=1.4.2=py_0
  - pygments=2.6.1=py_0
  - pymongo=3.9.0=py36he6710b0_0
  - pyopenssl=19.1.0=py36_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py36h22d08a2_1
  - pysocks=1.7.1=py36_0
  - python=3.6.10=hcf32534_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py36h7b6447c_0
  - pyyaml=5.3.1=py36h7b6447c_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=py36_0
  - scikit-image=0.16.2=py36h0573a6f_0
  - scikit-learn=0.22.1=py36hd81dba3_0
  - scipy=1.4.1=py36h0b6359f_0
  - setuptools=45.0.0=py36_1
  - sip=4.19.13=py36he6710b0_0
  - six=1.14.0=py36_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py36h7b6447c_1
  - traitlets=4.3.3=py36_0
  - urllib3=1.25.8=py36_0
  - wcwidth=0.1.9=py_0
  - wheel=0.34.2=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h3b9ef0a_2
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - cachetools==4.1.0
    - gast==0.2.2
    - google-auth==1.13.1
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.28.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.2.1
    - mudicom==0.1.2
    - numpy==1.18.2
    - oauthlib==3.1.0
    - opt-einsum==3.2.0
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - redis==3.4.1
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - tensorboard==2.1.1
    - tensorflow==2.1.0
    - tensorflow-estimator==2.1.0
    - termcolor==1.1.0
    - werkzeug==1.0.1
    - wrapt==1.12.1
prefix: /miniconda/envs/jarvis

